version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: talentiq-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: talentiq
    ports:
      - "5432:5432"

  chromadb:
    image: chromadb/chroma
    container_name: talentiq-chroma
    restart: always
    ports:
      - "8000:8000"